substitutions:
  display_model: "SH1107 128x128"
  display_rotation: "270"
  sun_latitude: 52.37°
  sun_longitude: 4.89°
  i2c_sda: GPIO48
  i2c_scl: GPIO47
  i2s_lrclk_pin : GPIO12
  i2s_bclk_pin: GPIO1
  i2s_dout_pin: GPIO2
  pin_a: GPIO9
  pin_b: GPIO10
  alarm_off_button_pin: GPIO4
  rotary_button_pin: GPIO8
  alarm_file: alarm.flac
  language: "NL"
  alarm_off_button_single_click_time: 1s
  timezone: Europe/Amsterdam

packages:
  remote_package_files:
    url: https://github.com/skons/soas
    files: [alarm-clock-soas.yaml, alarm-clock-espidf.yaml, alarm-clock-ds1307.yaml]

time:
  - id: !extend ntp
    timezone: ${timezone}
    servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org

select:
  - id: !extend alarm_stream_url
    options:
      - "http://playerservices.streamtheworld.com/api/livestream-redirect/RADIO538.mp3"
  - id: !extend alarm_stream_name
    options:
      - "538"

esphome:
  name: "alarm-clock-soas"
  friendly_name: "Alarm Clock SOAS"
  platformio_options:
    build_flags: "-DBOARD_HAS_PSRAM"
    board_build.arduino.memory_type: qio_opi

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  framework:
    type: esp-idf

api:
  encryption:
    key: "your encryption password"
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: "your ota string"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "alarm-clock-soas"
    password: "your ap password"

captive_portal:

psram:
  mode: octal
  speed: 80MHz